---
plugin: aws_ec2
environment:
  AWS_CONFIG_FILE: ~/.aws/credentials
regions:
  - us-east-1
strict: false
keyed_groups:
  - key: tags
    prefix: tag
  - key: tags.Name
    delimiter: '-'
    prefix: 'tag-Name'
hostnames:
  - ip-address
  - tag:Name
    delimiter: '-'
    prefix: 'tag-Name-'