---
plugin: aws_ec2
environment:
  AWS_CONFIG_FILE: ~/.aws/credentials
regions:
  - us-east-1
strict: false
keyed_groups:
  - key: tags.Name
    prefix: "tag_Name_"
hostnames:
  - ip-address
  - tag:Name