pipeline {
    agent any
    
    environment {
        DOCKER_REGISTRY = "https://hub.docker.com"
        DOCKER_REGISTRY_CREDENTIALS = credentials("mydockercredentials-id")
        DOCKER_IMAGE_NAME = "hello-world-java"
        DOCKER_IMAGE_TAG = "latest"
    }
    stages {
        stage('Clone repository') {
            steps {
                git 'https://github.com/AnriB/hello-world-java'
            }
        }
        
        stage('Build Docker image') {
            steps {
                script {
                    def image = docker.build('${env.DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}', '-f Dockerfile .')
                    docker.withRegistry(env.DOCKER_REGISTRY, env.DOCKER_REGISTRY_CREDENTIALS) {
                        image.push()
                    }
                }
            }
        }
        
        stage('Deploy to Kubernetes') {
            steps {
                
                }
            }
        }
    }
}